# -*- coding: utf-8 -*-
"""NLP_Task_ 3 (Chatbot using Transformers).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-FMypFvWbqajeI7zruYCS8PeU8fJ42J

Notebook Header & Metadata

#  NLP Task 3 – Chatbot using Hugging Face Transformers

## Objective
To build a conversational chatbot using a pre-trained transformer model from Hugging Face that can generate human-like responses.

## Tools Used
- Python
- Hugging Face Transformers
- PyTorch
- Google Colab

**Install Required Libraries**
"""

# INSTALL DEPENDENCIES
# Run this only once per environment
!pip install transformers torch accelerate -q

print("✅ Dependencies installed successfully!")

"""**Import Libraries**"""

# IMPORT NECESSARY LIBRARIES
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import sys

print(f"✅ PyTorch version: {torch.__version__}")
print(f"✅ Transformers library ready")

"""**Load Pre-trained Model & Tokenizer **"""

# MODEL LOADING - MANDATORY STEP
# Using DialoGPT-medium for balance of performance & memory usage
MODEL_NAME = "microsoft/DialoGPT-medium"  # Options: -small, -medium, -large

print(f"🔄 Loading model: {MODEL_NAME} ...")

# Load tokenizer and model from Hugging Face Hub
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

# Set model to evaluation mode
model.eval()

print("✅ Model and tokenizer loaded successfully!")
print(f"✅ Model device: {'CUDA' if torch.cuda.is_available() else 'CPU'}")

"""**Define Response Generation Function**"""

# RESPONSE GENERATION FUNCTION
def generate_bot_response(user_input, chat_history_ids, step):
    """
    Generate chatbot response using DialoGPT model

    Args:
        user_input (str): User's message
        chat_history_ids: Previous conversation tensor
        step (int): Current conversation turn number

    Returns:
        tuple: (bot_response_str, updated_chat_history_ids)
    """
    # Encode user input + EOS token
    new_input_ids = tokenizer.encode(
        user_input + tokenizer.eos_token,
        return_tensors='pt'
    )

    # Concatenate with chat history (if not first turn)
    bot_input_ids = torch.cat(
        [chat_history_ids, new_input_ids],
        dim=-1
    ) if step > 0 else new_input_ids

    # Generate response with sampling for better diversity
    # Parameters tuned for conversational quality
    chat_history_ids = model.generate(
        bot_input_ids,
        max_length=1000,              # Max tokens in response
        pad_token_id=tokenizer.eos_token_id,
        do_sample=True,               # Enable sampling (not greedy)
        top_k=50,                     # Sample from top 50 tokens
        top_p=0.95,                   # Nucleus sampling threshold
        temperature=0.7,              # Control randomness (0.7 = balanced)
        num_return_sequences=1        # Single response
    )

    # Decode and extract only the NEW response (skip history)
    bot_response = tokenizer.decode(
        chat_history_ids[:, bot_input_ids.shape[-1]:][0],
        skip_special_tokens=True
    )

    return bot_response, chat_history_ids

generate_bot_response("Hello", None, 0)

"""** Main Chat Loop Function**"""

# MAIN CHATBOT FUNCTION - CONVERSATION FLOW
def run_chatbot():
    """
    Interactive console chatbot with exit condition
    """
    print("\n" + "="*60)
    print("🤖 WELCOME TO YOUR AI ASSISTANT")
    print("="*60)
    print("💬 Type your message and press Enter")
    print("🚪 Type 'exit' or 'quit' to end conversation")
    print("="*60 + "\n")

    # Initialize chat history
    chat_history_ids = None
    step = 0

    while True:
        # Get user input
        user_input = input("👤 You: ").strip()

        # Exit condition check
        if user_input.lower() in ['exit', 'quit', 'bye', 'goodbye']:
            print("\n🤖 Chatbot: Thank you for chatting! Have a great day! 👋")
            print("="*60 + "\n")
            break

        # Skip empty inputs
        if not user_input:
            continue

        # Generate and display bot response
        try:
            bot_response, chat_history_ids = generate_bot_response(
                user_input,
                chat_history_ids,
                step
            )
            print(f"🤖 Chatbot: {bot_response}\n")
            step += 1

        except Exception as e:
            print(f"❌ Error generating response: {e}")
            print("💡 Tip: Try rephrasing your question\n")

run_chatbot()
